/* Manually generated by Eric :) */

pub const ANALYTIC_TYPE_SKA: ANALYTIC_TYPE = 0;
pub type ANALYTIC_TYPE = ::std::os::raw::c_uint;
extern "C" {
    pub fn ska_gpu_analytic_calc_jones(
        at: ANALYTIC_TYPE,
        d_azs: *const f64,
        d_zas: *const f64,
        num_directions: ::std::os::raw::c_int,
        d_freqs_hz: *const ::std::os::raw::c_uint,
        num_freqs: ::std::os::raw::c_int,
        pc_ra: f64,
        pc_dec: f64,
        num_stations: ::std::os::raw::c_int,
        d_station_coordinates: *const f64,
        d_station_angles: *const f64,
        d_num_elems_per_station: *const ::std::os::raw::c_int,
        lst_rad: f64,
        site_latitude_rad: f64,
        norm_to_zenith: u8,
        d_results: *mut ::std::os::raw::c_void,
    ) -> *const ::std::os::raw::c_char;
}
