/* Manually generated by Eric :) */

pub const ANALYTIC_TYPE_SKA: ANALYTIC_TYPE = 0;
pub type ANALYTIC_TYPE = ::std::os::raw::c_uint;
extern "C" {
    pub fn ska_gpu_analytic_calc_jones() -> *const ::std::os::raw::c_char;
}
